<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Magento\Framework\Escaper $escaper
 */
?>

<div class="category-grid">
    <div class="category-grid-title">
        <span class="title"><strong><?= $escaper->escapeHtml(__('Bekijk onze categorieën')) ?></strong></span>
    </div>
    <ul class="category-grid-content">
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image1.png')) ?>"
                     alt="Motoren_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Motoren" >
                        <?= $escaper->escapeHtml(__('Motoren')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image2.png')) ?>"
                     alt="Werkplaats_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Werkplaats">
                        <?= $escaper->escapeHtml(__('Werkplaats')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image3.png')) ?>"
                     alt="Onderdelen_accessoires_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Onderdelen-accessoires">
                        <?= $escaper->escapeHtml(__('Onderdelen & accessoires')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image4.png')) ?>"
                     alt="Oem_Parts_finder_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="OEM-Parts Finder">
                        <?= $escaper->escapeHtml(__('OEM-Parts Finder')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image5.png')) ?>"
                     alt="Onderhoud_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Onderhoud">
                        <?= $escaper->escapeHtml(__('Onderhoud')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image6.png')) ?>"
                     alt="Occassion_merken_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Occassion merken">
                        <?= $escaper->escapeHtml(__('Occassion merken')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image7.png')) ?>"
                     alt="Motorkleding_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Motorkleding">
                        <?= $escaper->escapeHtml(__('Motorkleding')) ?>
                    </a>
                </strong>
            </a>
        </li>
        <li class="category-item">
            <a href="#" class="category-item-info">
                <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Vendic_CategoryGrid::img/image8.png')) ?>"
                     alt="Motorhelmen_image"/>
                <strong class="category-item-name">
                    <a href="#" class="category-item-link" title="Motorhelmen">
                        <?= $escaper->escapeHtml(__('Motorhelmen')) ?>
                    </a>
                </strong>
            </a>
        </li>
    </ul>
</div>
